services:
  db:
    image: postgis/postgis:16-3.4
    container_name: adsb_db
    restart: always
    env_file:
      - envs/.local.env
      # - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data